#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
echo "spes"
if [ $# -eq 1 ]  ; then
	OUTPUT=$1
fi

GVF=${OUTPUT}PERF-VERSION-FILE

LF='
'

#
# First check if there is a .git to get the version from git describe
# otherwise try to get the version from the kernel Makefile
#
CID=
TAG=
if test -d ../../.git -o -f ../../.git
then
echo "spes1 TAG="$TAG
echo "spes1 CID="$CID
	TAG=$(git describe --abbrev=0 --match "v[0-9].[0-9]*" 2>/dev/null )
	CID=$(git log -1 --abbrev=12 --pretty=format:"%h" 2>/dev/null) && CID="-g$CID"
echo "spes2 TAG="$TAG
echo "spes3 CID="$CID
elif test -f ../../PERF-VERSION-FILE
then
	TAG=$(cut -d' ' -f3 ../../PERF-VERSION-FILE | sed -e 's/\"//g')
echo "spes4 TAG="$TAG
echo "spes5 CID="$CID
fi
if test -z "$TAG"
then
	TAG=$(MAKEFLAGS= make -sC ../.. kernelversion)
echo "spes6 TAG="$TAG
echo "spes7 CID="$CID
fi
VN="$TAG$CID"
if test -n "$CID"
then
	# format version string, strip trailing zero of sublevel:
	VN=$(echo "$VN" | sed -e 's/-/./g;s/\([0-9]*[.][0-9]*\)[.]0/\1/')
fi

VN=$(expr "$VN" : v*'\(.*\)')
echo "spes10 TAG="$TAG
echo "spes11 CID="$CID
if test -r $GVF
then
	VC=$(sed -e 's/^#define PERF_VERSION "\(.*\)"/\1/' <$GVF)
else
	VC=unset
fi
test "$VN" = "$VC" || {
	echo >&2 "  PERF_VERSION = $VN"
	echo "#define PERF_VERSION \"$VN\"" >$GVF
}


