#
# Makefile for the HISILICON network device drivers.
#

obj-$(CONFIG_HIX5HD2_GMAC) += hix5hd2_gmac.o
obj-$(CONFIG_HIP04_ETH) += hip04_mdio.o hip04_eth.o
obj-$(CONFIG_HIP05_GMAC) += hip05_mdio.o hip05_gmac.o
obj-$(CONFIG_HI_NET_VENDOR_NIC) += nic_drv/
obj-$(CONFIG_HNS) += hns/
