// SPDX-License-Identifier: GPL-2.0
// Copyright (C) 2018 - Arm Ltd

#ifndef __ASM_MPAM_HWDEF_H__
#define __ASM MPAM_HWDEF_H__

#include <linux/bitops.h>

/* CPU Registers */
#define MPAM_SYSREG_EN			63
#define MPAM_SYSREG_TRAP_LOWER		62
#define MPAM_SYSREG_TRAP_MPAM0_EL1	49
#define MPAM_SYSREG_TRAP_MPAM1_EL1	48
#define MPAM_SYSREG_PMG_D		GENMASK(47, 40)
#define MPAM_SYSREG_PMG_D_SHIFT	40
#define MPAM_SYSREG_PMG_I		GENMASK(39, 32)
#define MPAM_SYSREG_PMG_I_SHIFT	32
#define MPAM_SYSREG_PARTID_D		GENMASK(31, 16)
#define MPAM_SYSREG_PARTID_D_SHIFT	16
#define MPAM_SYSREG_PARTID_I		GENMASK(15, 0)
#define MPAM_SYSREG_PARTID_I_SHIFT	0

#define MPAMIDR_PMG_SHIFT		32
#define MPAMIDR_PMG_LEN			8
#define MPAMIDR_PMG_MASK		GENMASK(40, 32)
#define MPAMIDR_VPMR_SHIFT		18
#define MPAMIDR_VPMR_LEN		3
#define MPAMIDR_HAS_HCR			17
#define MPAMIDR_PARTID_SHIFT		0
#define MPAMIDR_PARTID_LEN		15
#define MPAMIDR_PARTID_MASK		GENMASK(15, 0)

#define MPAMHCR_EL0_VPMEN		0
#define MPAMHCR_EL1_VPMEN		1
#define MPAMHCR_GSTAPP_PLK		8
#define MPAMHCR_TRAP_MPAMIDR		31

/* Properties of the VPM registers */
#define MPAM_VPM_NUM_REGS		8
#define MPAM_VPM_PARTID_LEN		16
#define MPAM_VPM_PARTID_MASK		0xffff
#define MPAM_VPM_REG_LEN		64
#define MPAM_VPM_PARTIDS_PER_REG	(MPAM_VPM_REG_LEN / MPAM_VPM_PARTID_LEN)
#define MPAM_VPM_MAX_PARTID		(MPAM_VPM_NUM_REGS * MPAM_VPM_PARTIDS_PER_REG)

#endif /* __ASM_MPAM_HWDEF_H__ */
