dtb-$(CONFIG_ARCH_P660)		+= hisi_p660_evb.dtb hisi_p660_evb_pangea.dtb hip05-d02.dtb hip05-2p1s.dtb hip05-s01.dtb hip05-2p2s.dtb
dtb-$(CONFIG_ARCH_Hi1610)	+= hisi_hi1610.dtb hisi_hi1610_2p.dtb
dtb-$(CONFIG_ARCH_Hi1382)	+= hisi_hi1382_fpga.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
