dts-dirs += amd
dts-dirs += apm
dts-dirs += arm
dts-dirs += cavium
dts-dirs += exynos
dts-dirs += freescale
dts-dirs += mediatek
dts-dirs += qcom
dts-dirs += sprd
dts-dirs += xilinx
dts-dirs += hisilicon

subdir-y	:= $(dts-dirs)
